### ISSUE TITLE
The programming job interview

### ISSUE THREAD

**Issue by taddeimania** [developingfatigue/topics#7]
- Your experiences with interviewing for programming jobs
- What should new developers expect
- Differences between interviewing for entry vs. senior programming jobs
- Take home projects?
- White board algorithms?

Interviewing for a programming job is such a varied experience across all levels and roles. Some companies do it well, some companies are just trying to figure it out. I'd love to hear (in great detail) the high and low points of your interview experiences.

**Comment by williamsbdev** [comment]
Episode 8 - Released August 2:

http://developingfatigue.fm/show/8/interviewing
