### ISSUE TITLE
The human side of the code review

### ISSUE THREAD

**Issue by taddeimania** [developingfatigue/topics#8]
- What does it feel like to receive a highly critical code review
- What does it feel like to give a highly critical code review
- Strategies to avoid a stress response from someone receiving a code review
- How do you efficiently review code without falling down a time sink
- Reviews as part of the mentoring process

I feel like negative responses to a review or a code patch is a major contribution to keeping folks from engaging in open source. It's one of a developers biggest fears "What if they don't like what i've done?" - and results in many non starters. How do you (from both sides) engage in a welcoming but critical review, and alternatively what are strategies for a contributor to employ so they don't feel ostracized for trying to contribute work?

**Comment by toranb** [comment]
https://developingfatigue.fm/show/13/code-review
